name: Greetings

on: [pull_request, issues]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v3.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        pr_message:  'Hello @${{ github.actor }}, thank you for submitting a PR! We will respond as soon as possible.'
        issue_message: |
          Hello @${{ github.actor }}, thanks for contributing to the Password Pusher community!  We will respond as soon as possible.
